import Head from "next/head";
import { Hero } from "../components/sections/_home/Hero/Hero";
import { LandingLayout } from "../components/Layout/LandingLayout";
import { Courses } from "../components/sections/_home/Carrousel/Courses";
import { Pregatire } from "../components/sections/_home/Pregatire/Pregatire";

const Home = () => {
  return (
    <>
      <Head>
        <title>Cursuri IT cu certificare internationala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingLayout>
        <Hero />
        <Courses />
        <Pregatire />
        <section>landing pregatire angajare</section>
        <section>landing career steps</section>
        <section>landing about</section>
        <section>lanidng testimoniale</section>
      </LandingLayout>
    </>
  );
};

export default Home;
